export const QUOTES = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { text: "It is not the mountain we conquer but ourselves.", author: "Sir Edmund Hillary" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Our greatest glory is not in never failing, but in rising every time we fail.", author: "Confucius" },
  { text: "First, forget inspiration. Habit is more dependable.", author: "Octavia Butler" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "The quality of your life is determined by the quality of your questions.", author: "Tony Robbins" },
  { text: "Knowledge is not power. Applied knowledge is power.", author: "Dale Carnegie" },
  { text: "The chains of habit are too light to be felt until they are too heavy to be broken.", author: "Samuel Johnson" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "The present moment always will have been.", author: "Eckhart Tolle" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "Consistency is more important than intensity.", author: "Unknown" },
  { text: "A little better every day — that's all it takes.", author: "Unknown" },
  { text: "You don't rise to the occasion, you sink to your training.", author: "Navy SEAL saying" },
  { text: "The best investment you can make is in yourself.", author: "Warren Buffett" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Motivation gets you going. Habit keeps you growing.", author: "John C. Maxwell" },
];

export function getDailyQuote(): { text: string; author: string } {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
  return QUOTES[dayOfYear % QUOTES.length];
}
